---
title: "Class17"
format: pdf
author: Kyle Canturia (A17502778)
---

```{r}
library(tximport)
#set working directory via session>set working directory
# setup the folder and file-names to read
folders <- dir(pattern="SRR21568*")
samples <- sub("_quant", "", folders)
files <- file.path( folders, "abundance.h5" )
names(files) <- samples

txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)
```

```{r}
head(txi.kallisto$counts)
```
```{r}
colSums(txi.kallisto$counts)
sum(rowSums(txi.kallisto$counts)>0)
```

```{r}
#filter out transcripts without any reads
to.keep <- rowSums(txi.kallisto$counts) > 0
kset.nonzero <- txi.kallisto$counts[to.keep,]
#filter out transcripts with no change
keep2 <- apply(kset.nonzero,1,sd)>0
x <- kset.nonzero[keep2,]
```

# Principal Component Analysis

```{r}
pca <- prcomp(t(x), scale=TRUE)
summary(pca)
```
Plot for PC1 vs PC2
```{r}
plot(pca$x[,1], pca$x[,2],
     col=c("blue","blue","red","red"),
     xlab="PC1", ylab="PC2", pch=16)
```
Now using ggplot per lab sheet instructions:

Plot for PC1 vs PC2

```{r}
library(ggplot2)
#need to convert data into a dataframe
pca.dataframe <- data.frame(pca$x)

cols <- c("blue","blue","red","red")
ggplot(pca.dataframe) +
  aes(pca$x[,1], pca$x[,2]) +
  geom_point(color=cols) +
  labs(x="PCA1", y="PCA2")
```

Plot for PC1 vs PC3

```{r}
library(ggplot2)

cols <- c("blue","blue","red","red")
ggplot(pca.dataframe) +
  aes(pca$x[,1], pca$x[,3]) +
  geom_point(color=cols) +
  labs(x="PCA1", y="PCA3")
```


Plot for PC2 vs PC3

```{r}
cols <- c("blue","blue","red","red")
ggplot(pca.dataframe) +
  aes(pca$x[,2], pca$x[,3]) +
  geom_point(color=cols) +
  labs(x="PCA2", y="PCA3")
```